import { useCallback, useEffect, useState } from 'react'
import { getSettings, type AppLanguage } from './settings'

const dictionaries = {
  en: {
    currency: 'Currency',
    arrivalTime: 'Arrival time', arrivalHour: 'Arrival hour', arrivalMinute: 'Arrival minute', arrivalPeriod: 'AM or PM',
    backToList: 'Back to list',
    reactivateProperty: 'Activate', deleteProperty: 'Delete property', confirmDeleteProperty: 'Are you sure you want to permanently delete this property? Linked data may also be deleted.', propertyActionFailed: 'Unable to update or delete the property. Check access and linked records.',
    home: 'Home', calendar: 'Calendar', properties: 'Properties', newBooking: 'New Booking', reservation: 'Reservation', list: 'List', settings: 'Settings', logout: 'Logout',
    email: 'Email', password: 'Password', bookingManagement: 'Booking Management', welcomeBack: 'Welcome back', signInToManage: 'Sign in to manage your properties.',
    goodMorning: 'Good morning, Kate', todayOverview: "Today's operational overview.", checkIns: 'Check-ins', checkOuts: 'Check-outs', cleanings: 'Cleanings',
    availability: 'Availability', continuousTimeline: 'Continuous availability timeline.', fit: 'FIT', zoom: 'Zoom', previous: 'Previous period', next: 'Next period',
    portfolio: 'Portfolio', homesDetailsAvailability: 'Homes, access details and availability.', newProperty: 'New property', editProperty: 'Edit property', propertyDetails: 'Property details',
    addPropertyImage: 'Add property image', changeImage: 'Change image', removeImage: 'Remove image', imageHint: 'JPG, PNG or WEBP · max 2 MB',
    name: 'Name', color: 'Color', address: 'Address', city: 'City', guests: 'Guests', rooms: 'Rooms', area: 'Area', cleaning: 'Cleaning', checkIn: 'Check-in', checkOut: 'Check-out',
    notes: 'Notes', createProperty: 'Create property', saveChanges: 'Save changes', deactivate: 'Deactivate', active: 'Active', inactive: 'Inactive',
    regionalMeasurement: 'Regional & measurement', language: 'Language', measurementUnits: 'Measurement units', dateFormat: 'Date format', europeanDateFormat: 'DD.MM.YYYY (European)', americanDateFormat: 'MM/DD/YYYY (American)', appearance: 'Appearance',
    administration: 'Administration', agencyHint: 'Name, logo & regional defaults', people: 'People', calendarSources: 'Calendar Sources', notifications: 'Notifications', account: 'Account', propertiesHint: 'Homes, details & images', peopleHint: 'Roles & property access', calendarSourcesHint: 'Airbnb & Booking.com', notificationsHint: 'Arrival & cleaning alerts', accountHint: 'Profile & security', notificationsTitle: 'Notifications', notificationsDescription: 'Choose which operational reminders you receive.', cleaningReminders: 'Cleaning reminders', newReservationAlerts: 'New reservation alerts', saveNotifications: 'Save notifications', calendarSourcesTitle: 'Calendar Sources', calendarSourcesDescription: 'Store your Airbnb and Booking.com iCal links for the next sync step.', airbnbIcalUrl: 'Airbnb iCal URL', bookingIcalUrl: 'Booking.com iCal URL', saveCalendarSources: 'Save calendar sources', notSyncedYet: 'Links saved locally. Calendar sync will use these sources in the next integration pass.', accountTitle: 'Account', accountDescription: 'Signed-in account and session controls.', signedInAs: 'Signed in as', signOut: 'Sign out',
    chooseLooks: 'Choose how the app looks.', formattingIndependent: 'Formatting stays independent from interface language.',
    light: 'Light', dark: 'Dark', system: 'System', english: 'English', croatian: 'Hrvatski', metric: 'Metric (m², °C)', imperial: 'Imperial (ft², °F)',
    stay: 'Stay', guest: 'Guest', source: 'Source', directManual: 'Direct / Manual', agency: 'Agency', createBooking: 'Create booking', creatingBooking: 'Creating booking…',
    addressSearch: 'Start typing an address', addressFallback: 'You can also enter the address manually.', addressSearchError: 'Address search is temporarily unavailable. You can still enter the address manually.',
    searchMap: 'Search address', mapPreview: 'Map preview', selectLocation: 'Select a location',
    logoutTitle: 'Sign out', today: 'Today', tomorrow: 'Tomorrow', turnoverCleaning: 'Turnover cleaning', guestsLabel: 'guests', nightLabel: 'night', nightsLabel: 'nights', events: 'events', noEvents: 'No events', nothingScheduled: 'Nothing scheduled for this day.', loadingToday: 'Loading today...', dailyOverviewError: 'We couldn’t load your daily overview.', tryAgain: 'Try again', reservations: 'Reservations', guestsPage: 'Guests', blockDates: 'Block dates', tasksPage: 'Tasks', editReservation: 'Edit reservation', goToCalendar: 'Go to cal.', pricePerNight: 'Price per night', totalPrice: 'Total price', backupData: 'Data backup', backupDescription: 'Export or import application data.', exportDatabase: 'Export database', importDatabase: 'Import database', dailyOverview: 'Daily Overview', arrivals: 'Arrivals', departures: 'Departures',
    loading: 'Loading…', saving: 'Saving…', saved: 'Saved', cancel: 'Cancel', done: 'Done', add: 'Add', close: 'Close', search: 'Search', from: 'From', until: 'Until', type: 'Type', description: 'Description', status: 'Status', all: 'All', arriving: 'Arriving', departing: 'Departing',
    createBookingDescription: 'Create a direct or agency reservation.', unableLoadProperties: 'Unable to load properties.', bookingCreated: 'Booking created successfully.', unableCreateBooking: 'Could not create the booking.', overlappingBooking: 'These dates overlap another booking.', checkingAvailability: 'Checking availability…', selectProperty: 'Select a property.', selectCheckIn: 'Select a check-in date.', selectCheckOut: 'Select a check-out date.', guestsAtLeastOne: 'Guests must be at least 1.', optionalNotes: 'Optional notes',
    guestContactDetails: 'Guest contact & stay details', guestContactsUnavailable: 'Guest contacts could not be loaded.', guestSearchPlaceholder: 'Enter a new guest or find an existing guest', existingGuest: 'Existing guest', existingContactSelected: 'Existing contact selected.', useNewContact: 'Use a new contact instead', phone: 'Phone', guestLanguage: 'Guest language', country: 'Country', guestNotes: 'Guest notes', specialRequest: 'Special request', adults: 'Adults', children: 'Children', nightlyRate: 'Nightly rate', total: 'Total',
    datesBlocked: 'Dates blocked successfully.', viewBlocks: 'View availability blocks', endAfterStart: 'End date must be after start date.', unableBlockDates: 'Unable to block dates.', availableAgain: 'Available again', reason: 'Reason', blockDatesHint: 'The end date is available for a new arrival. Blocks cannot overlap existing reservations.',
    ownerStay: 'Owner stay', maintenance: 'Maintenance', problem: 'Problem', renovation: 'Renovation', notAvailable: 'Not available', other: 'Other', inspection: 'Inspection', linen: 'Linen', repair: 'Repair', delivery: 'Delivery', supplies: 'Supplies',
    reservationDetails: 'Reservation details', reservationNotFound: 'Reservation not found.', unableLoadReservation: 'Unable to load reservation.', unableLoadGuestContact: 'Unable to load guest contact. Reload before saving.', validNightlyRate: 'Enter a valid nightly rate.', enterGuestName: 'Enter the guest name.', checkOutAfterCheckIn: 'Check-out must be after check-in.', propertyGuestLimit: 'This property allows up to {count} guests.', reservationUpdated: 'Reservation updated.', unableSaveReservation: 'Unable to save reservation.', deleteReservationConfirm: 'Delete reservation for {name}?', unableDeleteReservation: 'Unable to delete reservation.', guestName: 'Guest name', importedReservationHint: 'Imported {source} reservations keep their source and guest fields read-only.',
    focusedBookingView: 'Focused booking view', booking: 'Booking', sort: 'SORT', sortProperties: 'Sort properties', zoomOut: 'Zoom out', zoomIn: 'Zoom in', fitOn: 'FIT on', fitOff: 'FIT off', fitTimelineTitle: 'Show a 3-month fitted timeline', on: 'ON', off: 'OFF', calendarHint: '100% keeps the current dense timeline. FIT shows 3 months. Double-click a reservation to edit it.', confirmDateChange: 'Confirm date change', areYouSure: 'Are you sure?', changeReservationTo: 'Change this reservation to {range}?', confirmChange: 'Confirm change', blockLoadError: 'Availability blocks could not be loaded. Refresh before planning a stay.', reservationLoadError: 'Reservation could not be loaded.', reservationOverlapError: 'This reservation overlaps another booking.', resizeSaveError: 'Could not save the new reservation dates. Changes were reverted.', importedReadOnly: 'Imported reservation — dates are read-only', resizeStart: 'Resize reservation start', resizeEnd: 'Resize reservation end',
    availabilityNext30: 'Next 30 days', scrollHorizontally: 'Scroll horizontally', previousMonth: 'Previous month', nextMonth: 'Next month',
    noAddress: 'No address', edit: 'Edit', view: 'View', closePropertyEditor: 'Close property editor', propertyPreview: 'Property preview', loadingProperties: 'Loading properties…', noProperties: 'No properties yet', createFirstProperty: 'Create your first property to start managing availability.', inactiveProperties: 'Inactive properties', propertyUpdated: 'Property updated.', propertyCreated: 'Property created.', propertyDeactivated: 'Property deactivated.', unableSaveProperty: 'Unable to save property. The property may have been saved; please check the list and edit it if needed.', unableDeactivateProperty: 'Unable to deactivate property.', unableReadImage: 'Unable to read image.', calendarLinks: 'Calendar links', loadingLinks: 'Loading links…', addCalendarLink: 'Add calendar link', calendarLinkAdded: 'Calendar link added.', calendarLinkUpdated: 'Calendar link updated.', calendarLinkRemoved: 'Calendar link removed.', unableLoadLinks: 'Unable to load calendar links.', unableAddLink: 'Unable to add calendar link.', unableUpdateLink: 'Unable to update calendar link.', unableRemoveLink: 'Unable to remove calendar link.', parking: 'Parking', keybox: 'Keybox',
    preferences: 'Preferences', settingsDescription: 'Appearance, regional formatting and administration.', openAdministrationSection: 'Open a section to manage the workspace.',
    searchOperations: 'Search name, reference or source', filterProperty: 'Filter property', allProperties: 'All properties', reservationFilter: 'Reservation filter', upcoming: 'Upcoming', current: 'Current', conflict: 'Conflict', confirmed: 'Confirmed', tentative: 'Tentative', cancelled: 'Cancelled', noReservations: 'No reservations found.', stays: 'stays', repeatGuest: 'Repeat guest', selectPropertyFirst: 'Select a property first.', unableLoadOperations: 'Unable to load operations. Check the database migration.', unableSaveOperation: 'Unable to save. Check dates and property access.', createTask: 'Create task', availableAgainShort: 'available again', removeBlockConfirm: 'Remove this availability block?', unblock: 'UNBLOCK', pending: 'Pending', inProgress: 'In progress',
    cleaningTasks: 'Cleaning tasks', availabilityBlocks: 'Availability blocks', profiles: 'Profiles',
    profile: 'Profile', saveProfile: 'Save profile', newPassword: 'New password', confirmPassword: 'Confirm password', updatePassword: 'Update password', dangerZone: 'Danger zone', dangerZoneDescription: 'Permanently delete your account. The last administrator is protected from self-deletion.', deleteMyAccount: 'Delete my account', deleting: 'Deleting…', unableLoadProfile: 'Unable to load account profile.', profileSaved: 'Profile saved.', unableSaveProfile: 'Unable to save profile.', passwordMinLength: 'Password must be at least 8 characters.', passwordsMismatch: 'Passwords do not match.', passwordUpdated: 'Password updated.', unableUpdatePassword: 'Unable to update password.', deleteAccountConfirm: 'Delete your account permanently? This cannot be undone.', unableDeleteAccount: 'Unable to delete account. The last administrator cannot delete their own account.',
    managePeople: 'Manage users, roles and property access.', addUser: 'Add user', loadingPeople: 'Loading people…', selectPerson: 'Select a person to manage access.', role: 'Role', propertyAccess: 'Property access', adminsGlobalAccess: 'Admins retain global access.', savePermissions: 'Save permissions', temporaryPassword: 'Temporary password', temporaryPasswordHint: 'Give this to the new user. They should change it in Account after signing in.', invitationHint: 'An invitation email will be sent to the new user.', sendInvitation: 'Send invitation', createUser: 'Create user', working: 'Working…', creating: 'Creating…', adminRole: 'Administrator', managerRole: 'Manager', viewerRole: 'Viewer', cleaningRole: 'Cleaning', adminRoleHint: 'Full administration and property access.', managerRoleHint: 'Operational editing on assigned properties.', viewerRoleHint: 'Read-only access to assigned properties.', cleaningRoleHint: 'Cleaning information without guest details.',
    rememberMe: 'Remember me', forgotPassword: 'Forgot password?', sending: 'Sending…', signIn: 'Sign in', signingIn: 'Signing in…', enterPassword: 'Enter your password', showPassword: 'Show password', hidePassword: 'Hide password', emailRequired: 'Email is required.', passwordRequired: 'Password is required.', enterEmailFirst: 'Enter your email first.', resetEmailSent: 'Password reset email sent.', calmManagement: 'A calmer way to manage homes, bookings and daily operations.', accountAccessUnavailable: 'Account access unavailable', accountAccessHint: 'Your account may be inactive, or access could not be verified. Contact your administrator or try again.', accessDenied: 'Access denied', roleNoAccess: 'Your role does not have access to this page.',
  },
  hr: {
    currency: 'Valuta',
    arrivalTime: 'Vrijeme dolaska', arrivalHour: 'Sat dolaska', arrivalMinute: 'Minute dolaska', arrivalPeriod: 'Prije ili poslije podne',
    backToList: 'Natrag na popis',
    reactivateProperty: 'Aktiviraj', deleteProperty: 'Izbriši nekretninu', confirmDeleteProperty: 'Jeste li sigurni da želite trajno izbrisati ovu nekretninu? Povezani podaci također mogu biti izbrisani.', propertyActionFailed: 'Nije moguće izmijeniti ili izbrisati nekretninu. Provjerite pristup i povezane zapise.',
    home: 'Početna', calendar: 'Kalendar', properties: 'Nekretnine', newBooking: 'Nova rezervacija', reservation: 'Rezervacija', list: 'Lista', settings: 'Postavke', logout: 'Odjava',
    email: 'E-mail', password: 'Lozinka', bookingManagement: 'Booking Management', welcomeBack: 'Dobro došli nazad', signInToManage: 'Prijavite se za upravljanje nekretninama.',
    goodMorning: 'Dobro jutro, Kate', todayOverview: 'Današnji operativni pregled.', checkIns: 'Dolazci', checkOuts: 'Odlasci', cleanings: 'Čišćenja',
    availability: 'Dostupnost', continuousTimeline: 'Kontinuirana vremenska linija rezervacija.', fit: 'UKLOPI', zoom: 'Zum', previous: 'Prethodni period', next: 'Sljedeći period',
    portfolio: 'Portfolio', homesDetailsAvailability: 'Nekretnine, detalji i dostupnost.', newProperty: 'Nova nekretnina', editProperty: 'Uredi nekretninu', propertyDetails: 'Detalji nekretnine',
    addPropertyImage: 'Dodaj sliku nekretnine', changeImage: 'Promijeni sliku', removeImage: 'Ukloni sliku', imageHint: 'JPG, PNG ili WEBP · max 2 MB',
    name: 'Naziv', color: 'Boja', address: 'Adresa', city: 'Grad', guests: 'Gostiju', rooms: 'Sobe', area: 'Površina', cleaning: 'Čišćenje', checkIn: 'Dolazak', checkOut: 'Odlazak',
    notes: 'Napomena', createProperty: 'Kreiraj nekretninu', saveChanges: 'Sačuvaj izmjene', deactivate: 'Deaktiviraj', active: 'Aktivna', inactive: 'Neaktivna',
    regionalMeasurement: 'Regionalno i mjere', language: 'Jezik', measurementUnits: 'Mjerne jedinice', dateFormat: 'Format datuma', europeanDateFormat: 'DD.MM.YYYY (evropski)', americanDateFormat: 'MM/DD/YYYY (američki)', appearance: 'Izgled',
    administration: 'Administracija', agencyHint: 'Naziv, logo i regionalne postavke', people: 'Ljudi', calendarSources: 'Izvori kalendara', notifications: 'Obavijesti', account: 'Račun', propertiesHint: 'Nekretnine, detalji i slike', peopleHint: 'Uloge i pristup nekretninama', calendarSourcesHint: 'Airbnb i Booking.com', notificationsHint: 'Dolazak i čišćenja', accountHint: 'Profil i sigurnost', notificationsTitle: 'Obavijesti', notificationsDescription: 'Odaberite operativne podsjetnike koje želite primati.', cleaningReminders: 'Podsjetnici za čišćenje', newReservationAlerts: 'Obavijesti o novim rezervacijama', saveNotifications: 'Sačuvaj obavijesti', calendarSourcesTitle: 'Izvori kalendara', calendarSourcesDescription: 'Sačuvajte Airbnb i Booking.com iCal linkove za sljedeći korak sinhronizacije.', airbnbIcalUrl: 'Airbnb iCal URL', bookingIcalUrl: 'Booking.com iCal URL', saveCalendarSources: 'Sačuvaj izvore kalendara', notSyncedYet: 'Linkovi su sačuvani lokalno. Sinhronizacija kalendara dolazi u sljedećem koraku.', accountTitle: 'Račun', accountDescription: 'Prijavljeni račun i kontrola sesije.', signedInAs: 'Prijavljeni korisnik', signOut: 'Odjavi se',
    chooseLooks: 'Odaberite izgled aplikacije.', formattingIndependent: 'Formatiranje je nezavisno od jezika sučelja.',
    light: 'Svijetlo', dark: 'Tamno', system: 'Sistem', english: 'English', croatian: 'Hrvatski', metric: 'Metrički (m², °C)', imperial: 'Imperijalni (ft², °F)',
    stay: 'Boravak', guest: 'Gost', source: 'Izvor', directManual: 'Direktno / Ručno', agency: 'Agencija', createBooking: 'Kreiraj rezervaciju', creatingBooking: 'Kreiranje rezervacije…',
    addressSearch: 'Počnite unositi adresu', addressFallback: 'Adresu možete unijeti i ručno.', addressSearchError: 'Pretraga adrese trenutno nije dostupna. Adresu možete unijeti ručno.',
    searchMap: 'Pretraži adresu', mapPreview: 'Pregled karte', selectLocation: 'Odaberite lokaciju',
    logoutTitle: 'Odjavi se', today: 'Danas', tomorrow: 'Sutra', turnoverCleaning: 'Čišćenje nakon odlaska', guestsLabel: 'gostiju', nightLabel: 'noć', nightsLabel: 'noći', events: 'događaja', noEvents: 'Nema događaja', nothingScheduled: 'Za ovaj dan nema planiranih aktivnosti.', loadingToday: 'Učitavanje današnjih podataka...', dailyOverviewError: 'Dnevni pregled nije moguće učitati.', tryAgain: 'Pokušaj ponovo', reservations: 'Rezervacije', guestsPage: 'Gosti', blockDates: 'Blokiraj datume', tasksPage: 'Zadaci', editReservation: 'Uredi rezervaciju', goToCalendar: 'Idi na kal.', pricePerNight: 'Cijena po noćenju', totalPrice: 'Ukupna cijena', backupData: 'Sigurnosna kopija podataka', backupDescription: 'Izvezite ili uvezite podatke aplikacije.', exportDatabase: 'Izvezi bazu', importDatabase: 'Uvezi bazu', dailyOverview: 'Dnevni pregled', arrivals: 'Dolazci', departures: 'Odlasci',
    loading: 'Učitavanje…', saving: 'Spremanje…', saved: 'Spremljeno', cancel: 'Odustani', done: 'Gotovo', add: 'Dodaj', close: 'Zatvori', search: 'Pretraži', from: 'Od', until: 'Do', type: 'Vrsta', description: 'Opis', status: 'Status', all: 'Sve', arriving: 'Dolazak', departing: 'Odlazak',
    createBookingDescription: 'Kreirajte direktnu ili agencijsku rezervaciju.', unableLoadProperties: 'Nekretnine nije moguće učitati.', bookingCreated: 'Rezervacija je uspješno kreirana.', unableCreateBooking: 'Rezervaciju nije moguće kreirati.', overlappingBooking: 'Ovi datumi se preklapaju s drugom rezervacijom.', checkingAvailability: 'Provjera dostupnosti…', selectProperty: 'Odaberite nekretninu.', selectCheckIn: 'Odaberite datum dolaska.', selectCheckOut: 'Odaberite datum odlaska.', guestsAtLeastOne: 'Broj gostiju mora biti najmanje 1.', optionalNotes: 'Neobavezna napomena',
    guestContactDetails: 'Kontakt gosta i detalji boravka', guestContactsUnavailable: 'Kontakte gostiju nije moguće učitati.', guestSearchPlaceholder: 'Unesite novog gosta ili pronađite postojećeg', existingGuest: 'Postojeći gost', existingContactSelected: 'Odabran je postojeći kontakt.', useNewContact: 'Koristi novi kontakt', phone: 'Telefon', guestLanguage: 'Jezik gosta', country: 'Država', guestNotes: 'Napomene o gostu', specialRequest: 'Poseban zahtjev', adults: 'Odrasli', children: 'Djeca', nightlyRate: 'Cijena po noćenju', total: 'Ukupno',
    datesBlocked: 'Datumi su uspješno blokirani.', viewBlocks: 'Pogledaj blokirane datume', endAfterStart: 'Završni datum mora biti nakon početnog.', unableBlockDates: 'Datume nije moguće blokirati.', availableAgain: 'Ponovno dostupno', reason: 'Razlog', blockDatesHint: 'Završni datum dostupan je za novi dolazak. Blokirani datumi ne smiju se preklapati s rezervacijama.',
    ownerStay: 'Boravak vlasnika', maintenance: 'Održavanje', problem: 'Problem', renovation: 'Renoviranje', notAvailable: 'Nije dostupno', other: 'Ostalo', inspection: 'Pregled', linen: 'Posteljina', repair: 'Popravak', delivery: 'Dostava', supplies: 'Potrepštine',
    reservationDetails: 'Detalji rezervacije', reservationNotFound: 'Rezervacija nije pronađena.', unableLoadReservation: 'Rezervaciju nije moguće učitati.', unableLoadGuestContact: 'Kontakt gosta nije moguće učitati. Ponovno učitajte stranicu prije spremanja.', validNightlyRate: 'Unesite ispravnu cijenu po noćenju.', enterGuestName: 'Unesite ime gosta.', checkOutAfterCheckIn: 'Odlazak mora biti nakon dolaska.', propertyGuestLimit: 'Ova nekretnina prima najviše {count} gostiju.', reservationUpdated: 'Rezervacija je ažurirana.', unableSaveReservation: 'Rezervaciju nije moguće spremiti.', deleteReservationConfirm: 'Izbrisati rezervaciju za gosta {name}?', unableDeleteReservation: 'Rezervaciju nije moguće izbrisati.', guestName: 'Ime gosta', importedReservationHint: 'Uvezene {source} rezervacije zadržavaju izvor, a podaci gosta i datumi ne mogu se mijenjati.',
    focusedBookingView: 'Prikaz odabrane rezervacije', booking: 'Rezervacija', sort: 'SORTIRAJ', sortProperties: 'Sortiraj nekretnine', zoomOut: 'Umanji', zoomIn: 'Povećaj', fitOn: 'UKLAPANJE uključeno', fitOff: 'UKLAPANJE isključeno', fitTimelineTitle: 'Prikaži uklopljenu vremensku liniju za 3 mjeseca', on: 'UKLJ.', off: 'ISKLJ.', calendarHint: '100% zadržava gusti prikaz. UKLOPI prikazuje 3 mjeseca. Dvaput kliknite rezervaciju za uređivanje.', confirmDateChange: 'Potvrda promjene datuma', areYouSure: 'Jeste li sigurni?', changeReservationTo: 'Promijeniti ovu rezervaciju na {range}?', confirmChange: 'Potvrdi promjenu', blockLoadError: 'Blokirane datume nije moguće učitati. Osvježite stranicu prije planiranja boravka.', reservationLoadError: 'Rezervaciju nije moguće učitati.', reservationOverlapError: 'Ova rezervacija preklapa se s drugom rezervacijom.', resizeSaveError: 'Nove datume nije moguće spremiti. Promjene su poništene.', importedReadOnly: 'Uvezena rezervacija — datumi se ne mogu mijenjati', resizeStart: 'Promijeni početak rezervacije', resizeEnd: 'Promijeni kraj rezervacije',
    availabilityNext30: 'Sljedećih 30 dana', scrollHorizontally: 'Pomaknite vodoravno', previousMonth: 'Prethodni mjesec', nextMonth: 'Sljedeći mjesec',
    noAddress: 'Nema adrese', edit: 'Uredi', view: 'Pogledaj', closePropertyEditor: 'Zatvori uređivanje nekretnine', propertyPreview: 'Pregled slike nekretnine', loadingProperties: 'Učitavanje nekretnina…', noProperties: 'Još nema nekretnina', createFirstProperty: 'Kreirajte prvu nekretninu za upravljanje dostupnošću.', inactiveProperties: 'Neaktivne nekretnine', propertyUpdated: 'Nekretnina je ažurirana.', propertyCreated: 'Nekretnina je kreirana.', propertyDeactivated: 'Nekretnina je deaktivirana.', unableSaveProperty: 'Nekretninu nije moguće spremiti. Možda je spremljena; provjerite popis i po potrebi je uredite.', unableDeactivateProperty: 'Nekretninu nije moguće deaktivirati.', unableReadImage: 'Sliku nije moguće učitati.', calendarLinks: 'Poveznice kalendara', loadingLinks: 'Učitavanje poveznica…', addCalendarLink: 'Dodaj poveznicu kalendara', calendarLinkAdded: 'Poveznica kalendara je dodana.', calendarLinkUpdated: 'Poveznica kalendara je ažurirana.', calendarLinkRemoved: 'Poveznica kalendara je uklonjena.', unableLoadLinks: 'Poveznice kalendara nije moguće učitati.', unableAddLink: 'Poveznicu kalendara nije moguće dodati.', unableUpdateLink: 'Poveznicu kalendara nije moguće ažurirati.', unableRemoveLink: 'Poveznicu kalendara nije moguće ukloniti.', parking: 'Parking', keybox: 'Kutija za ključeve',
    preferences: 'Postavke', settingsDescription: 'Izgled, regionalno formatiranje i administracija.', openAdministrationSection: 'Otvorite odjeljak za upravljanje radnim prostorom.',
    searchOperations: 'Pretraži ime, referencu ili izvor', filterProperty: 'Filtriraj nekretninu', allProperties: 'Sve nekretnine', reservationFilter: 'Filtar rezervacija', upcoming: 'Nadolazeće', current: 'Trenutne', conflict: 'Sukob', confirmed: 'Potvrđene', tentative: 'Privremene', cancelled: 'Otkazane', noReservations: 'Nema pronađenih rezervacija.', stays: 'boravaka', repeatGuest: 'Ponovni gost', selectPropertyFirst: 'Najprije odaberite nekretninu.', unableLoadOperations: 'Operativne podatke nije moguće učitati. Provjerite migraciju baze.', unableSaveOperation: 'Spremanje nije uspjelo. Provjerite datume i pristup nekretnini.', createTask: 'Kreiraj zadatak', availableAgainShort: 'ponovno dostupno', removeBlockConfirm: 'Ukloniti ovu blokadu dostupnosti?', unblock: 'ODBLOKIRAJ', pending: 'Na čekanju', inProgress: 'U tijeku',
    cleaningTasks: 'Zadaci čišćenja', availabilityBlocks: 'Blokirani datumi', profiles: 'Profili',
    profile: 'Profil', saveProfile: 'Spremi profil', newPassword: 'Nova lozinka', confirmPassword: 'Potvrdi lozinku', updatePassword: 'Ažuriraj lozinku', dangerZone: 'Opasna zona', dangerZoneDescription: 'Trajno izbrišite svoj račun. Posljednji administrator zaštićen je od samostalnog brisanja.', deleteMyAccount: 'Izbriši moj račun', deleting: 'Brisanje…', unableLoadProfile: 'Profil računa nije moguće učitati.', profileSaved: 'Profil je spremljen.', unableSaveProfile: 'Profil nije moguće spremiti.', passwordMinLength: 'Lozinka mora imati najmanje 8 znakova.', passwordsMismatch: 'Lozinke se ne podudaraju.', passwordUpdated: 'Lozinka je ažurirana.', unableUpdatePassword: 'Lozinku nije moguće ažurirati.', deleteAccountConfirm: 'Trajno izbrisati vaš račun? Ova radnja ne može se poništiti.', unableDeleteAccount: 'Račun nije moguće izbrisati. Posljednji administrator ne može izbrisati vlastiti račun.',
    managePeople: 'Upravljajte korisnicima, ulogama i pristupom nekretninama.', addUser: 'Dodaj korisnika', loadingPeople: 'Učitavanje korisnika…', selectPerson: 'Odaberite osobu za upravljanje pristupom.', role: 'Uloga', propertyAccess: 'Pristup nekretninama', adminsGlobalAccess: 'Administratori imaju pristup svim nekretninama.', savePermissions: 'Spremi ovlasti', temporaryPassword: 'Privremena lozinka', temporaryPasswordHint: 'Predajte je novom korisniku. Treba je promijeniti u Računu nakon prijave.', invitationHint: 'Novom korisniku bit će poslan poziv e-poštom.', sendInvitation: 'Pošalji poziv', createUser: 'Kreiraj korisnika', working: 'Obrada…', creating: 'Kreiranje…', adminRole: 'Administrator', managerRole: 'Upravitelj', viewerRole: 'Pregledavatelj', cleaningRole: 'Čišćenje', adminRoleHint: 'Potpuna administracija i pristup nekretninama.', managerRoleHint: 'Operativno uređivanje dodijeljenih nekretnina.', viewerRoleHint: 'Pristup samo za čitanje dodijeljenih nekretnina.', cleaningRoleHint: 'Podaci o čišćenju bez detalja gosta.',
    rememberMe: 'Zapamti me', forgotPassword: 'Zaboravili ste lozinku?', sending: 'Slanje…', signIn: 'Prijava', signingIn: 'Prijava…', enterPassword: 'Unesite lozinku', showPassword: 'Prikaži lozinku', hidePassword: 'Sakrij lozinku', emailRequired: 'E-mail je obavezan.', passwordRequired: 'Lozinka je obavezna.', enterEmailFirst: 'Najprije unesite e-mail.', resetEmailSent: 'Poruka za obnovu lozinke je poslana.', calmManagement: 'Mirniji način upravljanja nekretninama, rezervacijama i dnevnim poslovima.', accountAccessUnavailable: 'Pristup računu nije dostupan', accountAccessHint: 'Vaš račun možda nije aktivan ili pristup nije moguće potvrditi. Obratite se administratoru ili pokušajte ponovno.', accessDenied: 'Pristup odbijen', roleNoAccess: 'Vaša uloga nema pristup ovoj stranici.',
  },
} satisfies Record<AppLanguage, Record<string, string>>

type TranslationKey = keyof typeof dictionaries.en

const valueDictionaries: Record<AppLanguage, Record<string, string>> = {
  en: {},
  hr: {
    'Owner stay': 'Boravak vlasnika', Maintenance: 'Održavanje', Problem: 'Problem', Renovation: 'Renoviranje', 'Not available': 'Nije dostupno', Other: 'Ostalo',
    Cleaning: 'Čišćenje', Inspection: 'Pregled', Linen: 'Posteljina', Repair: 'Popravak', Delivery: 'Dostava', Supplies: 'Potrepštine',
    direct: 'direktno', agency: 'agencija', confirmed: 'potvrđena', tentative: 'privremena', cancelled: 'otkazana', pending: 'na čekanju', in_progress: 'u tijeku', done: 'završeno',
  },
}

export function translate(language: AppLanguage, key: TranslationKey, variables?: Record<string, string | number>): string {
  const value = dictionaries[language][key]
  if (!variables) return value
  return Object.entries(variables).reduce((result, [name, replacement]) => result.replaceAll(`{${name}}`, String(replacement)), value)
}

export function translateValue(language: AppLanguage, value: string): string {
  return valueDictionaries[language][value] ?? value
}

export function useAppLanguage(): AppLanguage {
  const [language, setLanguage] = useState<AppLanguage>(() => getSettings().language)
  useEffect(() => {
    const handle = () => setLanguage(getSettings().language)
    window.addEventListener('booking-manager-settings-change', handle)
    return () => window.removeEventListener('booking-manager-settings-change', handle)
  }, [])
  return language
}

export function useT() {
  const language = useAppLanguage()
  return useCallback((key: TranslationKey, variables?: Record<string, string | number>) => translate(language, key, variables), [language])
}
