import { useEffect, useMemo, useState } from 'react'
import type { FormEvent } from 'react'
import { CalendarDays, FileText, UserRound, UsersRound } from 'lucide-react'
import { DatePicker } from '../components/DatePicker'
import { useNavigate } from 'react-router-dom'
import { getProperties, type Property } from '../lib/properties-repository'
import { getReservations } from '../lib/reservations-repository'
import { createReservationWithCleaning } from '../lib/booking-workflow'
import { findBookingConflict, validateBookingForm, type BookingFormValues } from '../lib/reservation-form'
import { formatDateRange } from '../lib/date-format'
import { useT } from '../lib/i18n'

function todayString() { const d=new Date(); return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}` }
const initial: BookingFormValues = { propertyId:'', checkIn:todayString(), checkOut:todayString(), guestName:'', guests:1, source:'direct', notes:'' }

export function NewBookingPage() {
  const t=useT(); const navigate=useNavigate(); const [properties,setProperties]=useState<Property[]>([]); const [form,setForm]=useState<BookingFormValues>(initial); const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false); const [error,setError]=useState<string|null>(null); const [message,setMessage]=useState<string|null>(null)
  useEffect(()=>{getProperties().then(items=>{setProperties(items);setForm(current=>({...current,propertyId:current.propertyId||items[0]?.id||''}));setLoading(false)}).catch(()=>{setError('Unable to load properties.');setLoading(false)})},[])
  const selectedProperty=useMemo(()=>properties.find(p=>p.id===form.propertyId),[properties,form.propertyId])
  function update<K extends keyof BookingFormValues>(key:K,value:BookingFormValues[K]){setForm(current=>({...current,[key]:value}))}
  async function handleSubmit(event:FormEvent<HTMLFormElement>){event.preventDefault();setError(null);setMessage(null);const validationError=validateBookingForm(form,selectedProperty);if(validationError){setError(validationError);return}setSaving(true);try{const reservations=await getReservations(`${form.checkIn}T00:00:00`,`${form.checkOut}T23:59:59.999`);if(findBookingConflict(reservations,form)){setError('These dates overlap another booking.');return}if(!selectedProperty){setError('Select a property.');return}await createReservationWithCleaning({property_id:form.propertyId,source:form.source,guest_name:form.guestName.trim(),check_in:new Date(`${form.checkIn}T${selectedProperty.check_in_time.slice(0,5)}:00`).toISOString(),check_out:new Date(`${form.checkOut}T${selectedProperty.check_out_time.slice(0,5)}:00`).toISOString(),guests:form.guests,status:'confirmed',notes:form.notes.trim()||null},selectedProperty.cleaning_duration_minutes);setMessage('Booking created successfully.');setTimeout(()=>navigate('/calendar'),500)}catch{setError('Could not create the booking.')}finally{setSaving(false)}}
  if(loading)return <section className="mx-auto max-w-3xl p-3 md:p-5"><p className="text-xs text-slate-500">Loading...</p></section>
  return <section className="mx-auto max-w-3xl p-3 pb-8 md:p-5"><header className="mb-4"><p className="text-[10px] font-semibold uppercase tracking-[0.18em] text-violet-500">Reservations</p><h1 className="mt-1 text-3xl font-semibold sm:text-4xl tracking-tight">{t('newBooking')}</h1><p className="mt-1 text-xs text-slate-500">Create a direct or agency reservation.</p></header><form onSubmit={handleSubmit} className="space-y-3">
    <section className="rounded-[1.35rem] bg-white p-4"><div className="flex items-center gap-2 text-sm font-semibold"><CalendarDays size={17} className="text-violet-500"/>{t('stay')}</div><div className="mt-3 grid gap-3 md:grid-cols-2"><label className="text-[11px] font-semibold text-slate-600 md:col-span-2">{t('properties')}<select id="property" value={form.propertyId} onChange={e=>update('propertyId',e.target.value)} className="mt-1 w-full rounded-xl border border-slate-200 bg-white px-3 py-2.5 text-sm font-normal outline-none focus:border-violet-400">{properties.map(property=><option key={property.id} value={property.id}>{property.name} · {property.capacity}</option>)}</select></label>
      <label className="text-[11px] font-semibold text-slate-600">{t('checkIn')}<DatePicker label={t('checkIn')} value={form.checkIn} onChange={(value)=>update('checkIn',value)}/></label>
      <label className="text-[11px] font-semibold text-slate-600">{t('checkOut')}<DatePicker label={t('checkOut')} value={form.checkOut} onChange={(value)=>update('checkOut',value)}/></label>
    </div><p className="mt-2 rounded-xl bg-slate-50 px-3 py-2 text-[11px] font-semibold text-slate-500">{formatDateRange(`${form.checkIn}T12:00:00`,`${form.checkOut}T12:00:00`)}</p></section>
    <section className="rounded-[1.35rem] bg-white p-4"><div className="flex items-center gap-2 text-sm font-semibold"><UserRound size={17} className="text-violet-500"/>{t('guest')}</div><div className="mt-3 grid gap-3 md:grid-cols-2"><label className="text-[11px] font-semibold text-slate-600 md:col-span-2">Guest name<input id="guest-name" value={form.guestName} onChange={e=>update('guestName',e.target.value)} placeholder="Guest name" className="mt-1 w-full rounded-xl border border-slate-200 px-3 py-2.5 text-sm font-normal"/></label><label className="text-[11px] font-semibold text-slate-600">{t('guests')}<input id="guests" type="number" min={1} max={selectedProperty?.capacity} value={form.guests} onChange={e=>update('guests',Number(e.target.value))} className="mt-1 w-full rounded-xl border border-slate-200 px-3 py-2.5 text-sm font-normal"/></label><label className="text-[11px] font-semibold text-slate-600">{t('source')}<select id="source" value={form.source} onChange={e=>update('source',e.target.value as 'direct'|'agency')} className="mt-1 w-full rounded-xl border border-slate-200 bg-white px-3 py-2.5 text-sm font-normal"><option value="direct">{t('directManual')}</option><option value="agency">{t('agency')}</option></select></label></div></section>
    <section className="rounded-[1.35rem] bg-white p-4"><div className="flex items-center gap-2 text-sm font-semibold"><FileText size={17} className="text-violet-500"/>{t('notes')}</div><textarea id="notes" rows={3} value={form.notes} onChange={e=>update('notes',e.target.value)} placeholder="Optional notes" className="mt-2 w-full resize-none rounded-xl border border-slate-200 px-3 py-2.5 text-sm outline-none focus:border-violet-400"/></section>
    {error&&<div role="alert" className="rounded-xl border border-rose-200 bg-rose-50 px-3 py-2.5 text-xs font-medium text-rose-700">{error}</div>}{message&&<div role="status" className="rounded-xl border border-emerald-200 bg-emerald-50 px-3 py-2.5 text-xs font-medium text-emerald-700">{message}</div>}
    <button type="submit" disabled={saving} className="flex w-full items-center justify-center gap-2 rounded-xl bg-violet-600 px-4 py-3 text-xs font-semibold text-white hover:bg-violet-700 disabled:opacity-60"><UsersRound size={15}/>{saving?t('creatingBooking'):t('createBooking')}</button>
  </form></section>
}
